services:
  # Backend Service
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "9090:9090"
    env_file:
      - .env
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    networks:
      - mern

  # Frontend Service
  frontend:
    # build: ./frontend

    build: 
      context: ./frontend
      args:
        - NEXT_LOCAL_BACKEND_URL=http://localhost:9090

    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    depends_on:
      - backend
    networks:
      - mern

networks:
  mern:
    driver: bridge

